name: router_example
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  feature_home_api:
    path: ../features/feature_home/api
  feature_home_ui:
    path: ../features/feature_home/ui
  feature_login_api:
    path: ../features/feature_login/api
  feature_login_ui:
    path: ../features/feature_login/ui
  feature_splash_api:
    path: ../features/feature_splash/api
  feature_splash_ui:
    path: ../features/feature_splash/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true