name: feature_home_api
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  core_navigation_api:
    path: ../../../core/navigation/api

dev_dependencies:
  flutter_lints: ^2.0.0